<a href="https://colab.research.google.com/github/subrhamanya-2701/Automation-Shoe-Counter/blob/main/Final_software_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install face_recognition

     |████████████████████████████████| 100.1 MB 25 kB/s 
  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566186 sha256=7160e43451058d074af20b980e69ffe96bedda9f40a86bbda61d2839ddf764ad
  Stored in directory: /root/.cache/pip/wheels/d6/81/3c/884bcd5e1c120ff548d57c2ecc9ebf3281c9a6f7c0e7e7947a
Successfully built face-recognition-models


In [4]:
import imutils
import numpy as np
import cv2
from google.colab.patches import cv2_imshow
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import os
import time
import face_recognition

In [5]:
def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [19]:
# Trail find number
def find_number1(list_1):
  #print(list_1)
  for i in list(range(1, 7)):
    if str(i) not in list_1:
      return i

In [20]:
def read_img(path):
  image = cv2.imread(path)
  (h, w) = image.shape[:2]
  width = 500
  ratio = width / float(w)
  height = int(h * ratio)
  return cv2.resize(image, (width, height))

Make folder : '/content/drive/MyDrive/Experimet_project/'

In that folder make another folder which has address **"/content/drive/MyDrive/MiniProject/ Colab Notebooks"** (Name is "Colab Notebooks") "Yours May be different --- **Google Colab** Used store some file in this file , we should make this folder before it create automatically.

In [35]:
Known = '/content/drive/MyDrive/Experimet_project/Known/'
while(True):
  #Known2 = '/content/drive/MyDrive/TRAIL/Known'
  print("************** -- Welcome to Shoe Counter -- **********")
  Option = input("----- Please Choose Your Option -----\n pick or keep : ")
  if Option == 'keep': 
    listf = []
    # Accesiing all file name in folders
    list_of_file = os.listdir(Known)
    #print(list_of_file)

    file_number = 0
    for b, dirs, f in os.walk(Known):
      for file1 in f:
        file_number+=1

    if file_number > 5:
      print("Ooooopss The Box is full Please try Another Table")
    else:
      if file_number > 0:
        for file_1 in list_of_file(Known):
          file_1 = file_1.split('.')
          file_2 = file_1[0]
          file_2 = file_2.split('_')
          listf.append(file_2[0])
      elif file_number == 0:
            listf.append(0)
      print(listf)

      print("Please Come infront of our Camara")
      image_file = take_photo()
      # img = cv2.imread('loadimage.jpeg')
      print("---------------Thank You---------------")
    
      image = cv2.imread(image_file)
      (h, w) = image.shape[:2]
      width = 500
      ratio = width / float(w)
      height = int(h * ratio)
      image = cv2.resize(image, (width, height))

      box = find_number1(list(listf))

      name = input("Enter your name : ")

      cv2.imwrite(Known + str(box) + "_" + name + '.jpeg', image)
      print("Please Keep Box number on Box Number : " + str(box))
      ## Stepper Motor Will Trun
      ##############
      ##############
      time.sleep(4)
      print("Thank You have Good day")
  elif Option == "pick":
    file_number = 0
    for b, dirs, f in os.walk(Known):
      for file1 in f:
        file_number+=1
    
    if file_number > 0:
      print("Please Come In front of Camara")
      image_file = take_photo()
      image = cv2.imread(image_file)
      (h, w) = image.shape[:2]
      width = 500
      ratio = width / float(w)
      height = int(h * ratio)
      img = cv2.resize(image, (width, height))

      #cv2.imwrite(temp + "unknown" + '.jpeg', image)
      #print("unknown--------" ,img)

      known_encoding = []
      known_names = []
      known_dir = Known



      #img = cv2.imread(temp + "unknown.jpeg")
      #img_enc_1 = face_recognition.face_encodings(img)

      # li = os.listdir(known_dir)
      # li.remove('.ipynb_checkpoints')
      # print(li)

      for file in os.listdir(known_dir)[1:]:
        #print(Known + file)
        img_1 = read_img(known_dir + file)
        print(img_1)
        img_enc = face_recognition.face_encodings(img_1)[0]
        print(f'{file} : ', img_enc)
        known_encoding.append(img_enc)
        #results = face_recognition.compare_faces(unknown_encoding, known_encoding)
        known_names.append(file.split('.')[0])

      print(img)

      img_enc_1 = face_recognition.face_encodings(img[0])

      print("Encoded image : ", img_enc_1)

      result = face_recognition.compare_faces(known_encoding, img_enc_1)
      distance = list(face_recognition.face_distance(known_encoding, img_enc_1))
      print(distance)
      file_name = known_names[distance.index(min(distance))]
      #(known_names[distance.index(min(distance))).split('_')[1]]
      if min(distance) < 3.33:
        print("----------***************************************************----------")
        print(f"Hii {file_name.split('_')[1]} Your Shoe is Comming, Please wait till Box number : {file_name.split('_')[0]}")
        print("----------***************************************************----------")
      else:
        print("Cannot recognising Face Please Try Agian")
    else:
      print("There is Noo file to Pick")
  else:
    print("***Please Choose valid Choice***\n ***Thank You***")

************** -- Welcome to Shoe Counter -- **********
----- Please Choose Your Option -----
 pick or keep : pick
Please Come In front of Camara


<IPython.core.display.Javascript object>

[[[139 142 140]
  [140 143 141]
  [138 143 142]
  ...
  [114 120 119]
  [116 122 121]
  [117 123 122]]

 [[142 145 143]
  [136 141 139]
  [136 141 140]
  ...
  [114 120 119]
  [116 122 121]
  [117 123 122]]

 [[137 142 140]
  [135 142 139]
  [138 144 143]
  ...
  [114 119 120]
  [116 121 122]
  [117 122 123]]

 ...

 [[ 26  22  33]
  [ 27  23  34]
  [ 26  22  33]
  ...
  [ 30  28  27]
  [ 33  31  30]
  [ 31  29  28]]

 [[ 27  23  34]
  [ 27  23  34]
  [ 26  22  33]
  ...
  [ 31  29  28]
  [ 36  34  33]
  [ 35  33  32]]

 [[ 26  22  33]
  [ 26  22  33]
  [ 25  22  31]
  ...
  [ 30  29  25]
  [ 35  34  30]
  [ 34  33  29]]]
2_subrhamanya.jpeg :  [-0.24456827  0.1294789   0.07309672 -0.04524456 -0.08225588 -0.03698364
 -0.02491405 -0.09943628  0.09174585 -0.06514995  0.23418972 -0.03725216
 -0.16492276 -0.15983111  0.04481793  0.06561334 -0.15558329 -0.17340773
 -0.04324625 -0.12023474  0.03932881  0.03081733 -0.03593307  0.04901974
 -0.21249744 -0.30785218 -0.04867273 -0.13569155  0.0175

TypeError: ignored

In [71]:
known_encoding

[[array([-0.24456827,  0.1294789 ,  0.07309672, -0.04524456, -0.08225588,
         -0.03698364, -0.02491405, -0.09943628,  0.09174585, -0.06514995,
          0.23418972, -0.03725216, -0.16492276, -0.15983111,  0.04481793,
          0.06561334, -0.15558329, -0.17340773, -0.04324625, -0.12023474,
          0.03932881,  0.03081733, -0.03593307,  0.04901974, -0.21249744,
         -0.30785218, -0.04867273, -0.13569155,  0.01752314, -0.14170173,
          0.01509363,  0.0303898 , -0.1859974 , -0.02059738, -0.01396531,
          0.17363656,  0.03289816,  0.08159301,  0.10234283, -0.02751131,
         -0.13838674, -0.06128749,  0.09154001,  0.30635279,  0.24671701,
          0.03730904, -0.05043131,  0.04315095,  0.11173731, -0.18877637,
          0.06112105,  0.07143011,  0.14949399,  0.06276699,  0.06645711,
         -0.1592637 , -0.04520224,  0.07192539, -0.15023075,  0.09859286,
          0.01209665, -0.1678414 , -0.11072274, -0.01841669,  0.29046243,
          0.07955594, -0.14588097, -0.

In [66]:
unknown = '/content/drive/MyDrive/Experimet_project/unknown/'
#image_file = take_photo()
# image = cv2.imread(image_file)
# (h, w) = image.shape[:2]
# width = 500
# ratio = width / float(w)
# height = int(h * ratio)
# img = cv2.resize(image, (width, height))
# print('take photo : ', img)
# cv2.imwrite(unknown + "unknown.jpeg", img)

image = face_recognition.load_image_file(unknown + "unknown.jpeg")
print(image)

face_location = face_recognition.face_locations(image)
face_encoding = face_recognition.face_encodings(image)[



# unknown_enc = []
# img_enc_1 = face_recognition.face_encodings('/content/drive/MyDrive/Experimet_project/unknown/unknown.jpeg')
# print("img_enc_1 :" , img_enc_1)
# unknown_enc = unknown_enc.append(img_enc_1)
print(face_encoding)



# def read_img(path):
#   image = cv2.imread(path)
#   (h, w) = image.shape[:2]
#   width = 500
#   ratio = width / float(w)
#   height = int(h * ratio)
#   return cv2.resize(image, (width, height))



# img = read_img(Known + '2_subrhamanya.jpeg')
# print(img)
# face_recognition.face_encodings(img)

[[[ 98 101  94]
  [ 98 100  95]
  [ 98 100  95]
  ...
  [ 65  69  68]
  [ 65  69  68]
  [ 65  69  68]]

 [[ 98 101  94]
  [ 98 100  95]
  [ 99 100  95]
  ...
  [ 64  68  67]
  [ 63  67  66]
  [ 63  67  66]]

 [[ 98 101  94]
  [ 98 101  94]
  [100 101  95]
  ...
  [ 63  67  66]
  [ 62  66  65]
  [ 61  65  64]]

 ...

 [[ 35  26  27]
  [ 35  26  27]
  [ 35  26  29]
  ...
  [ 22  27  30]
  [ 17  22  25]
  [ 13  18  21]]

 [[ 33  24  27]
  [ 33  24  27]
  [ 34  25  28]
  ...
  [ 22  27  30]
  [ 16  21  24]
  [ 11  16  19]]

 [[ 31  22  25]
  [ 31  22  25]
  [ 33  24  27]
  ...
  [ 23  28  31]
  [ 17  22  25]
  [  9  17  19]]]
[]


In [69]:
print(unknown + "unknown.jpeg")
unknown_encoding = []
img_1 = read_img('/content/drive/MyDrive/Experimet_project/unknown/unknown.jpeg')
print(img_1)
img_enc = face_recognition.face_encodings(img_1)
unknown_encoding.append(img_enc)
unknown_encoding

/content/drive/MyDrive/Experimet_project/unknown/unknown.jpeg
[[[ 95 100  98]
  [ 95 100  98]
  [ 95 100  99]
  ...
  [ 68  69  65]
  [ 68  69  65]
  [ 68  69  65]]

 [[ 95 100  98]
  [ 95 100  98]
  [ 95 100  99]
  ...
  [ 67  68  64]
  [ 66  67  63]
  [ 66  67  63]]

 [[ 94 101  98]
  [ 94 101  98]
  [ 95 101 100]
  ...
  [ 66  67  63]
  [ 65  66  62]
  [ 64  65  61]]

 ...

 [[ 27  26  35]
  [ 27  26  35]
  [ 29  26  35]
  ...
  [ 30  27  22]
  [ 25  22  17]
  [ 21  18  13]]

 [[ 25  24  33]
  [ 25  24  33]
  [ 28  25  34]
  ...
  [ 30  27  22]
  [ 24  21  16]
  [ 19  16  11]]

 [[ 25  22  31]
  [ 25  22  31]
  [ 27  24  33]
  ...
  [ 31  28  23]
  [ 25  23  15]
  [ 19  17   9]]]


[[]]

In [19]:
li = os.listdir(Known)
print(li)
print(li.remove('.ipynb_checkpoints'))
li

['1_siddha.jpeg', '.ipynb_checkpoints', '2_subha.jpeg', '3_subhaa.jpeg']
None


['1_siddha.jpeg', '2_subha.jpeg', '3_subhaa.jpeg']

In [43]:
unknown = '/content/drive/MyDrive/Experimet_project/unknown/'
img_enc_1 = take_photo()
print(img_enc_1)
img = read_img(unknown + img_enc_1)
cv2.imwrite( unknown + img_enc_1, img)
img_enc_1 = face_recognition.face_encodings(unknown + 'photo.jpg')

<IPython.core.display.Javascript object>

photo.jpg


AttributeError: ignored

In [18]:
#known_image = face_recognition.load_image_file("photo.jpg")
import face_recognition
unknown_image = face_recognition.load_image_file('/content/photo.jpg')
print(unknown_image)

# biden_encoding = face_recognition.face_encodings(known_image)[0]
unknown_encoding = face_recognition.face_encodings(unknown_image)

results = face_recognition.compare_faces(known_encoding, unknown_encoding)

[[[104 100  91]
  [103  99  90]
  [101  97  88]
  ...
  [103 105 104]
  [103 105 104]
  [103 105 104]]

 [[102  98  89]
  [102  98  89]
  [101  97  88]
  ...
  [103 105 104]
  [104 106 105]
  [105 107 106]]

 [[101  97  88]
  [101  97  88]
  [101  98  89]
  ...
  [103 105 104]
  [105 107 106]
  [106 108 107]]

 ...

 [[137  99 114]
  [136  98 113]
  [135  97 112]
  ...
  [ 50  52  75]
  [ 50  50  76]
  [ 50  50  76]]

 [[134  96 111]
  [135  97 112]
  [135  97 112]
  ...
  [ 51  51  75]
  [ 50  50  76]
  [ 50  50  76]]

 [[133  95 110]
  [134  96 111]
  [134  96 111]
  ...
  [ 50  50  74]
  [ 50  50  76]
  [ 50  50  76]]]


TypeError: ignored

In [13]:
known_encoding

[[array([-0.24456827,  0.1294789 ,  0.07309672, -0.04524456, -0.08225588,
         -0.03698364, -0.02491405, -0.09943628,  0.09174585, -0.06514995,
          0.23418972, -0.03725216, -0.16492276, -0.15983111,  0.04481793,
          0.06561334, -0.15558329, -0.17340773, -0.04324625, -0.12023474,
          0.03932881,  0.03081733, -0.03593307,  0.04901974, -0.21249744,
         -0.30785218, -0.04867273, -0.13569155,  0.01752314, -0.14170173,
          0.01509363,  0.0303898 , -0.1859974 , -0.02059738, -0.01396531,
          0.17363656,  0.03289816,  0.08159301,  0.10234283, -0.02751131,
         -0.13838674, -0.06128749,  0.09154001,  0.30635279,  0.24671701,
          0.03730904, -0.05043131,  0.04315095,  0.11173731, -0.18877637,
          0.06112105,  0.07143011,  0.14949399,  0.06276699,  0.06645711,
         -0.1592637 , -0.04520224,  0.07192539, -0.15023075,  0.09859286,
          0.01209665, -0.1678414 , -0.11072274, -0.01841669,  0.29046243,
          0.07955594, -0.14588097, -0.